steps:
- id: "yarn-install"
  name: "node:10"
  entrypoint: yarn
  args: ["install"]
- id: "yarn-build"
  name: "node:10"
  entrypoint: yarn
  args: ["build"]
- id: "gcloud-app-deploy"
  name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
