steps:
- id: "install"
  name: "node:10"
  entrypoint: yarn
  args: ["install"]

steps:
- id: "build"
  name: "node:10"
  entrypoint: yarn
  args: ["build"]

steps:
- id: "deploy"
  name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
